### ISSUE TITLE
PKGBUILD issues

### ISSUE THREAD

**Issue by hartwork** [aryklein/mkinitcpio-growrootfs#1]
Hi!

```
# Maintainer: Greg Sutcliffe <..........>
```

I believe that should be you now.

```
pkgrel=4
```

I believe this should be bumped to 5 or more. It's at 4 sinc 2013 in the version you forked from, already:
https://github.com/GregSutcliffe/aur-projects/commit/8476c54299e4a304e3fd04570046be844ddb3554

```
pkgdesc="mkinitcpio hook to autoscale the rootfs to the size of the partition"
```

To my understanding, it not only resizes the file system but the partition too. Actually that's the part that cloud-init cannot take over so `pkgdesc` could use an update in that regard.

Thanks!

**Comment by aryklein** [comment]
I took your advice. Changes was pushed to the repository.
Thanks

**Comment by hartwork** [comment]
Thanks! For the record, the related commit is e5c9b2d88a89d230f322e3fee3be1607c96de85d.
