### ISSUE TITLE
UUID= device support?

### ISSUE THREAD

**Issue by hartwork** [aryklein/mkinitcpio-growrootfs#2]
The source you forked from has one ticket open as of today. It is [issue 13: mkinitcpio-growrootfs doesn't understand UUID=foo](https://github.com/GregSutcliffe/aur-projects/issues/13). The [last comment](https://github.com/GregSutcliffe/aur-projects/issues/13#issuecomment-30371513) points to a patch used with ec2 images.

What do you think about it?

**Comment by rlees85** [comment]
Didn't see this issue. I think my PR fixes it though...

https://github.com/aryklein/mkinitcpio-growrootfs/pull/4

**Comment by aryklein** [comment]
Sorry. Long time not using this code. I'm not sure if it's still working. Arch Linux is a rolling release and it's complicated to maintain over time.

**Comment by hartwork** [comment]
Ary, if the code is no longer maintained, could you add an all-uppercase note where it reads "No description, website, or topics provided." right now?

**Comment by hartwork** [comment]
I overlooked that the code got merged. Ouch! I'll remove my earlier misleading comments. Sorry!

**Comment by rlees85** [comment]
https://gitlab.com/rlees85/packer-scripts/tree/working

I could tell these things are not maintained so much I just included them statically in my project and removed the resize2fs bits. Cloud-init takes care of that and supports BTRFS as well as EXT4.

This hook is still really useful for sorting out the partition though... and works :+1:
